services:
  - type: web
    name: p2pwallet
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn p2pwallet.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: p2pwallet
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4